## Where the samples will be written
save_data: data/SMILES_aug/SMILES_aug
## Where the vocab(s) will be written
src_vocab: data/SMILES_aug/SMILES_aug.vocab.src
tgt_vocab: data/SMILES_aug/SMILES_aug.vocab.tgt
share_vocab: True

src_seq_length: 1000
tgt_seq_length: 1000
src_vocab_size: 1000
tgt_vocab_size: 1000


# Corpus opts:
data:
    corpus_1:
        path_src: data/SMILES_aug/src-train.txt
        path_tgt: data/SMILES_aug/tgt-train.txt
    valid:
        path_src: data/SMILES_aug/src-val.txt
        path_tgt: data/SMILES_aug/tgt-val.txt
